apiVersion: v2
appVersion: "1.0"
description: A Helm chart for hmi-libra-dtu App
name: hmi-libra-dtu
home: https://github.com/hmcts/hmi-libra-dtu
version: 0.0.11
maintainers:
  - name: HMCTS HMI team
dependencies:
  - name: function
    version: 2.3.4
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
